version: '3.8'

services:
  app:
    build: .
    container_name: discord-game-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gamedb
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - discord-game-network

  postgres:
    image: postgres:15-alpine
    container_name: discord-game-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gamedb
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - discord-game-network

volumes:
  postgres-data:

networks:
  discord-game-network:
    driver: bridge